@startuml Titre
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------

class Etudiant {
nom
prenom
}
@enduml